version: '3'
services:
  cassandra-0:
    image: gcr.io/arcus-238802/arcus/cassandra:latest
    environment:
    - CASSANDRA_SEEDS=cassandra-0
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - CASSANDRA_DC=DC1
    - MAX_HEAP_SIZE=256M
    - HEAP_NEWSIZE=256M
    ports:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9160
    volumes:
    - cassandra-storage-0:/data
    networks:
      arcus:
        ipv4_address: 192.168.1.10
    deploy:
      restart_policy:
        condition: always
        delay: 5s
        max_attempts: 5
        window: 120s
  zookeeper-0:
    image: zookeeper:3.6
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=192.168.1.13:2888:3888;2181
    ports:
    - 2181
    volumes:
    - zookeeper-0:/data
    networks:
      arcus:
        ipv4_address: 192.168.1.13
  kafka-0:
    image: gcr.io/arcus-238802/arcus/kafka:latest
    environment:
      ZOOKEEPER: zookeeper-0:2181
      ZOOKEEPEROPS: zookeeper-0:2181
      KAFKA_HSIZE: 512
      KAFKA_BROKER_ID: 1
      ADVERTISED_HSTN: 192.168.1.14
      KAFAOPS_METRICS_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_SEGMENT_BYTES: 10485760
      KAFAOPS_METRICS_LOG_RETENTION_MS: 3600000
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_RETENTION_MS: 3600000
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_BROKER_RACK: dc1
      KAFKA_REPLICATOR_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
      KAFKA_PROTOCOL_VERSION: 2.3
    restart: on-failure
    ports:
    - 9092
    volumes:
    - kafka-0:/data
    networks:
      arcus:
        ipv4_address: 192.168.1.14

volumes:
  cassandra-storage-0:
  cassandra-storage-1:
  cassandra-storage-2:
  zookeeper-0:
  kafka-0:

networks:
  private:

  arcus:
    driver: macvlan
    driver_opts:
      parent: br0
    ipam:
      config:
      - subnet: 192.168.1.1/24
